// src/features/Notifications/services/notification.service.ts
//
// Talks to the real `notifications` table (see sql/migration.sql).
// Notifications for orders/appointments/customers are generated by
// database triggers, not by this file — that way they still fire even
// if nobody has this page open. The one thing generated client-side is
// the "new login" event, fired from AuthContext on SIGNED_IN.

import { supabase } from "../../../lib/supabase";
import { getActiveBusinessId } from "../../../lib/business";

import type {
  AppNotification,
  NotificationCategory,
  NotificationFilter,
  NotificationSettings,
} from "../types/notification";
import { DEFAULT_NOTIFICATION_SETTINGS } from "../types/notification";

const CACHE_KEY = "seba_notifications_cache";
const OUTBOX_KEY = "seba_notifications_outbox"; // queued mark-as-read/delete while offline

async function getBusinessId(): Promise<string> {
  return getActiveBusinessId();
}

function readCache(): AppNotification[] {
  try {
    const raw = localStorage.getItem(CACHE_KEY);
    return raw ? (JSON.parse(raw) as AppNotification[]) : [];
  } catch {
    return [];
  }
}

function writeCache(items: AppNotification[]) {
  try {
    localStorage.setItem(CACHE_KEY, JSON.stringify(items.slice(0, 200)));
  } catch {
    // storage full/unavailable - non-fatal
  }
}

type OutboxAction =
  | { type: "read"; id: string }
  | { type: "read_all" }
  | { type: "delete"; id: string };

function readOutbox(): OutboxAction[] {
  try {
    const raw = localStorage.getItem(OUTBOX_KEY);
    return raw ? (JSON.parse(raw) as OutboxAction[]) : [];
  } catch {
    return [];
  }
}

function writeOutbox(actions: OutboxAction[]) {
  try {
    localStorage.setItem(OUTBOX_KEY, JSON.stringify(actions));
  } catch {
    // ignore
  }
}

function queueAction(action: OutboxAction) {
  const outbox = readOutbox();
  outbox.push(action);
  writeOutbox(outbox);
}

export const notificationService = {
  /** Cached list for instant/offline render, refreshed by list(). */
  getCached(): AppNotification[] {
    return readCache();
  },

  async list(filter: NotificationFilter = "all"): Promise<AppNotification[]> {
    if (!navigator.onLine) {
      const cached = readCache();
      return applyFilter(cached, filter);
    }

    const businessId = await getBusinessId();

    let query = supabase
      .from("notifications")
      .select("*")
      .eq("business_id", businessId)
      .order("created_at", { ascending: false })
      .limit(200);

    if (filter === "unread") query = query.eq("read", false);
    else if (filter !== "all") query = query.eq("category", filter);

    const { data, error } = await query;
    if (error) {
      // network hiccup mid-request - fall back to cache instead of a blank page
      return applyFilter(readCache(), filter);
    }

    const rows = (data ?? []) as AppNotification[];
    // Cache the unfiltered "all" view so offline mode has the full picture.
    if (filter === "all") writeCache(rows);
    return rows;
  },

  async unreadCount(): Promise<number> {
    if (!navigator.onLine) {
      return readCache().filter((n) => !n.read).length;
    }
    const businessId = await getBusinessId();
    const { count, error } = await supabase
      .from("notifications")
      .select("id", { count: "exact", head: true })
      .eq("business_id", businessId)
      .eq("read", false);

    if (error) return readCache().filter((n) => !n.read).length;
    return count ?? 0;
  },

  async markAsRead(id: string): Promise<void> {
    // Optimistic local update so the UI feels instant and works offline.
    const cached = readCache().map((n) =>
      n.id === id ? { ...n, read: true, read_at: new Date().toISOString() } : n
    );
    writeCache(cached);

    if (!navigator.onLine) {
      queueAction({ type: "read", id });
      return;
    }

    await supabase
      .from("notifications")
      .update({ read: true, read_at: new Date().toISOString() })
      .eq("id", id);
  },

  async markAllAsRead(): Promise<void> {
    const businessId = await getBusinessId();
    const cached = readCache().map((n) => ({
      ...n,
      read: true,
      read_at: n.read_at ?? new Date().toISOString(),
    }));
    writeCache(cached);

    if (!navigator.onLine) {
      queueAction({ type: "read_all" });
      return;
    }

    await supabase
      .from("notifications")
      .update({ read: true, read_at: new Date().toISOString() })
      .eq("business_id", businessId)
      .eq("read", false);
  },

  /** Delete with undo — mirrors the pattern used in the Customers module. */
  async remove(id: string): Promise<void> {
    writeCache(readCache().filter((n) => n.id !== id));

    if (!navigator.onLine) {
      queueAction({ type: "delete", id });
      return;
    }

    await supabase.from("notifications").delete().eq("id", id);
  },

  async restore(notification: AppNotification): Promise<void> {
    writeCache([notification, ...readCache()]);
    if (navigator.onLine) {
      await supabase.from("notifications").insert(notification);
    }
  },

  /** Replays queued offline actions once the connection comes back. */
  async flushOutbox(): Promise<void> {
    if (!navigator.onLine) return;
    const outbox = readOutbox();
    if (outbox.length === 0) return;

    const businessId = await getBusinessId();

    for (const action of outbox) {
      try {
        if (action.type === "read") {
          await supabase
            .from("notifications")
            .update({ read: true, read_at: new Date().toISOString() })
            .eq("id", action.id);
        } else if (action.type === "read_all") {
          await supabase
            .from("notifications")
            .update({ read: true, read_at: new Date().toISOString() })
            .eq("business_id", businessId)
            .eq("read", false);
        } else if (action.type === "delete") {
          await supabase.from("notifications").delete().eq("id", action.id);
        }
      } catch {
        // leave remaining actions queued, try again next time we're online
      }
    }
    writeOutbox([]);
  },

  /** Client-side event: fired from AuthContext on SIGNED_IN (real logins
   *  can't be caught by a DB trigger on `auth.users` in the same simple
   *  way orders/appointments can, since Supabase Auth owns that schema). */
  async recordLogin(params: { businessId: string; who: string }): Promise<void> {
    if (!navigator.onLine) return; // login events aren't queued offline - you can't log in offline anyway
    await supabase.from("notifications").insert({
      business_id: params.businessId,
      category: "auth" as NotificationCategory,
      severity: "info",
      title: "New login",
      body: `${params.who} signed in`,
      link: null,
      entity_type: "auth",
      entity_id: null,
    });
  },

  /**
   * Subscribes to realtime notification inserts for the active business.
   * Call the returned function to unsubscribe (e.g. in a useEffect cleanup).
   * Matches the exact pattern used by orderService.subscribeToOrders().
   */
  async subscribe(onInsert: (n: AppNotification) => void): Promise<() => void> {
    const businessId = await getBusinessId();

    const channel = supabase
      .channel(`notifications-${businessId}-${crypto.randomUUID()}`)
      .on(
        "postgres_changes",
        {
          event: "INSERT",
          schema: "public",
          table: "notifications",
          filter: `business_id=eq.${businessId}`,
        },
        (payload) => {
          const row = payload.new as AppNotification;
          writeCache([row, ...readCache()]);
          onInsert(row);
        }
      )
      .subscribe();

    let removed = false;

    return () => {
      if (removed) return;
      removed = true;
      supabase.removeChannel(channel);
    };
  },

  // ---- Settings ----

  async getSettings(): Promise<NotificationSettings> {
    const businessId = await getBusinessId();
    const {
      data: { user },
    } = await supabase.auth.getUser();
    if (!user) throw new Error("Not signed in");

    const { data, error } = await supabase
      .from("notification_settings")
      .select("*")
      .eq("user_id", user.id)
      .eq("business_id", businessId)
      .maybeSingle();

    if (error || !data) {
      return {
        user_id: user.id,
        business_id: businessId,
        updated_at: null,
        ...DEFAULT_NOTIFICATION_SETTINGS,
      };
    }
    return data as NotificationSettings;
  },

  async saveSettings(settings: NotificationSettings): Promise<void> {
    await supabase.from("notification_settings").upsert({
      ...settings,
      updated_at: new Date().toISOString(),
    });
  },
};

function applyFilter(
  items: AppNotification[],
  filter: NotificationFilter
): AppNotification[] {
  if (filter === "all") return items;
  if (filter === "unread") return items.filter((n) => !n.read);
  return items.filter((n) => n.category === filter);
}

// Flush any queued offline actions as soon as connectivity returns.
if (typeof window !== "undefined") {
  window.addEventListener("online", () => {
    void notificationService.flushOutbox();
  });
}
